"""Local LLM client for SovereignOps using live Ollama + MCP agent loop.

Connects directly to local Ollama instance (air-gapped) and spawns local MCP server
(mcp/server.py) for live tool execution and structured inference.
"""

import sys
import json
import logging
import asyncio
import concurrent.futures
from pathlib import Path
from typing import Any, Dict, Optional, Union

import ollama
from mcp.client.session import ClientSession
from mcp.client.stdio import StdioServerParameters, stdio_client

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
MCP_SERVER_SCRIPT = PROJECT_ROOT / "mcp" / "server.py"

DEFAULT_MODEL = "llama3.1"


def map_mcp_tool_to_ollama(tool) -> dict:
    """Convert an MCP Tool definition into the Ollama function tool JSON schema."""
    input_schema = getattr(tool, "inputSchema", getattr(tool, "input_schema", {}))
    return {
        "type": "function",
        "function": {
            "name": tool.name,
            "description": tool.description or "",
            "parameters": input_schema,
        },
    }


async def query_mcp_agent_async(
    prompt_string: str,
    model: str = DEFAULT_MODEL,
) -> Dict[str, Any]:
    """Execute live Ollama LLM + MCP agent loop over stdio transport.

    Spawns mcp/server.py, maps tools, queries Ollama, executes tool calls,
    and returns a parsed dictionary.
    """
    server_params = StdioServerParameters(
        command=sys.executable,
        args=[str(MCP_SERVER_SCRIPT)],
        env=None,
    )

    system_prompt = (
        "You are an autonomous air-gapped site reliability engineering agent.\n"
        "Use the provided tools if helpful to investigate logs, runbooks, or commands.\n"
        "You MUST output ONLY a valid JSON object. Do not include markdown code fences or conversational text outside the JSON.\n"
    )

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": prompt_string},
    ]

    async with stdio_client(server_params) as (read_stream, write_stream):
        async with ClientSession(read_stream, write_stream) as session:
            await session.initialize()

            # Retrieve tools from MCP server
            tools_result = await session.list_tools()
            mapped_tools = [map_mcp_tool_to_ollama(tool) for tool in tools_result.tools]

            # 1. First Ollama LLM inference pass
            response = ollama.chat(
                model=model,
                messages=messages,
                tools=mapped_tools,
            )

            response_msg = response.get("message", {})
            tool_calls = response_msg.get("tool_calls", [])
            messages.append(response_msg)

            # 2. Execute any tool calls generated by Ollama
            if tool_calls:
                for call in tool_calls:
                    function_data = call.get("function", {})
                    tool_name = function_data.get("name")
                    tool_args = function_data.get("arguments", {})

                    logger.info(f"[MCP Agent] Executing tool '{tool_name}' with args {tool_args}")
                    result = await session.call_tool(tool_name, arguments=tool_args)

                    content_text = ""
                    for content_item in result.content:
                        if hasattr(content_item, "text"):
                            content_text += content_item.text + "\n"
                        else:
                            content_text += str(content_item) + "\n"

                    messages.append({
                        "role": "tool",
                        "content": content_text.strip(),
                    })

                # 3. Second Ollama LLM pass with tool results
                final_response = ollama.chat(
                    model=model,
                    messages=messages,
                    tools=mapped_tools,
                    format="json",
                )
                final_content = final_response.get("message", {}).get("content", "{}")
            else:
                final_content = response_msg.get("content", "{}")

            # Parse structured JSON output
            try:
                return json.loads(final_content)
            except json.JSONDecodeError:
                clean_text = final_content.strip()
                if "```json" in clean_text:
                    clean_text = clean_text.split("```json")[1].split("```")[0].strip()
                elif "```" in clean_text:
                    clean_text = clean_text.split("```")[1].split("```")[0].strip()
                return json.loads(clean_text)


def query_local_llm(
    context: Union[Dict[str, Any], str],
    fallback: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Execute live Ollama + MCP agent loop for local LLM inference.

    Args:
        context: Context dictionary or prompt string.
        fallback: Optional fallback payload (used if Ollama LLM is offline).

    Returns:
        Dict adhering to Contract C / D schema.
    """
    if isinstance(context, str):
        prompt_string = context
    elif isinstance(context, dict) and "prompt" in context and isinstance(context["prompt"], str):
        prompt_string = context["prompt"]
    else:
        prompt_string = f"Context Data:\n{json.dumps(context, indent=2)}"

    try:
        try:
            loop = asyncio.get_running_loop()
        except RuntimeError:
            loop = None

        if loop and loop.is_running():
            with concurrent.futures.ThreadPoolExecutor() as pool:
                result = pool.submit(lambda: asyncio.run(query_mcp_agent_async(prompt_string))).result()
                return result
        else:
            return asyncio.run(query_mcp_agent_async(prompt_string))
    except Exception as exc:
        logger.warning(f"Ollama/MCP agent loop error ({exc}). Falling back if available.")
        if fallback is not None:
            return fallback

        if "tier_1" in str(context).lower():
            return {
                "action_type": "tier_1_diagnostic",
                "payload": {
                    "command": "journalctl -u gateway-proxy -n 50",
                    "target_node": "api-gateway-01",
                },
            }
        return {
            "action_type": "tier_2_remediation",
            "payload": {
                "command": "kubectl rollout undo deployment/auth-service",
                "justification": "Graph mapped fault to auth-service timeout. Historical provenance score 0.94 strongly supports rollback.",
                "target_node": "auth-service",
            },
        }
